# Generated by Django 4.2.1 on 2023-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=240, null=True)),
                ('airport_name', models.CharField(max_length=240, null=True)),
                ('iata_code', models.CharField(max_length=240, null=True)),
                ('icao_code', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
