# Generated by Django 4.2.1 on 2023-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0002_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=240, null=True)),
                ('flight_number', models.CharField(max_length=240, null=True)),
                ('aircraft_reg', models.CharField(max_length=240, null=True)),
                ('departure_airport', models.CharField(max_length=240, null=True)),
                ('arrival_airport', models.CharField(max_length=240, null=True)),
                ('departure_time', models.CharField(max_length=240, null=True)),
                ('arrival_time', models.CharField(max_length=240, null=True)),
                ('departure_date', models.CharField(max_length=240, null=True)),
                ('arrival_date', models.CharField(max_length=240, null=True)),
                ('flight_category', models.CharField(max_length=240, null=True)),
                ('flight_type', models.CharField(max_length=240, null=True)),
                ('Via1', models.CharField(max_length=240, null=True)),
                ('Via2', models.CharField(max_length=240, null=True)),
                ('Via3', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
