# Generated by Django 4.2.1 on 2023-05-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0005_flight_charts_flight_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_charts',
            name='task_status',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
