# Generated by Django 4.2.1 on 2023-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0006_flight_charts_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_charts',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight_charts',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight_charts',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight_charts',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
    ]
