# Generated by Django 4.2.1 on 2023-05-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0007_alter_flight_charts_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_charts',
            name='departure_airport_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.airport'),
        ),
    ]
