# Generated by Django 4.2.1 on 2023-05-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0008_flight_charts_departure_airport_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_charts',
            name='arrival_airport_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='falcon_app.airport'),
        ),
        migrations.AlterField(
            model_name='flight_charts',
            name='departure_airport_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='falcon_app.airport'),
        ),
    ]
