# Generated by Django 4.2.1 on 2023-05-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0014_passenger_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_db',
            name='fligh_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.flight_charts'),
        ),
    ]
