# Generated by Django 4.2.1 on 2023-05-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0015_passenger_db_fligh_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger_db',
            old_name='fligh_id',
            new_name='flight_id',
        ),
    ]
