# Generated by Django 4.2.1 on 2023-05-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0016_rename_fligh_id_passenger_db_flight_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_charts',
            old_name='arrival_airport',
            new_name='operator',
        ),
        migrations.RemoveField(
            model_name='flight_charts',
            name='airline_name',
        ),
        migrations.RemoveField(
            model_name='flight_charts',
            name='departure_airport',
        ),
        migrations.AlterField(
            model_name='flight_charts',
            name='aircraft_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.aircraft'),
        ),
    ]
