# Generated by Django 4.2.1 on 2023-05-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0017_rename_arrival_airport_flight_charts_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_charts',
            name='flight_passengers_check_in',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='flight_charts',
            name='flight_passengers_to_check_in',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
