# Generated by Django 4.2.1 on 2023-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0018_flight_charts_flight_passengers_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_db',
            name='bag_weight',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='passenger_db',
            name='bags',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='passenger_db',
            name='hand_bag',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='passenger_db',
            name='pax_type',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='passenger_db',
            name='pax_weight',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
