# Generated by Django 4.2.1 on 2023-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0020_passenger_db_address_passenger_db_board_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_db',
            name='date_of_birth',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
