# Generated by Django 4.2.1 on 2023-06-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0021_alter_passenger_db_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_db',
            name='pax_type',
            field=models.CharField(default='Adult', max_length=240, null=True),
        ),
    ]
