# Generated by Django 4.2.1 on 2023-06-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0022_alter_passenger_db_pax_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger_lagage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='0000000000', max_length=100)),
                ('bag_type', models.CharField(max_length=240, null=True)),
                ('weight', models.CharField(max_length=240, null=True)),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.flight_charts')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.passenger_db')),
            ],
        ),
    ]
