# Generated by Django 4.2.1 on 2023-06-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0023_passenger_lagage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_1A', models.CharField(default='0', max_length=10)),
                ('s_1B', models.CharField(default='0', max_length=10)),
                ('s_1C', models.CharField(default='0', max_length=10)),
                ('s_1D', models.CharField(default='0', max_length=10)),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='falcon_app.flight_charts')),
            ],
        ),
    ]
