# Generated by Django 4.2.1 on 2023-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0024_flight_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_seat',
            name='s_2A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_2B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_2C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_2D',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
