# Generated by Django 4.2.1 on 2023-06-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0025_flight_seat_s_2a_flight_seat_s_2b_flight_seat_s_2c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_seat',
            name='s_10A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_10B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_10C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_10D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_11A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_11B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_11C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_11D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_12A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_12B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_12C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_12D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_13A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_13B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_13C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_13D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_14A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_14B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_14C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_14D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_15A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_15B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_15C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_15D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_16A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_16B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_16C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_16D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_17A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_17B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_17C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_17D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_18A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_18B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_18C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_18D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_19A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_19B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_19C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_19D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_20A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_20B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_20C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_20D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_3A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_3B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_3C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_3D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_4A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_4B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_4C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_4D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_5A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_5B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_5C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_5D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_6A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_6B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_6C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_6D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_7A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_7B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_7C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_7D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_8A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_8B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_8C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_8D',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_9A',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_9B',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_9C',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='flight_seat',
            name='s_9D',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
