# Generated by Django 4.2.1 on 2023-06-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0027_alter_passenger_db_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_db',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
