# Generated by Django 4.2.1 on 2023-07-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0028_passenger_db_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=240, null=True)),
                ('added_date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
