# Generated by Django 4.2.1 on 2023-07-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0029_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_db',
            name='status',
            field=models.CharField(default='0', max_length=240),
        ),
    ]
