# Generated by Django 4.2.1 on 2023-07-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0030_alter_passenger_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_db',
            name='qrid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
