# Generated by Django 4.2.1 on 2023-07-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon_app', '0031_passenger_db_qrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_db',
            name='board_dateandtime',
            field=models.DateTimeField(null=True),
        ),
    ]
